# github.com/go-task/task

version: '2'

tasks:
  build:
      dependencies: 
        - build-widget
      cmds:
          - pnpx babel src -d lib

  build-widget:
      cmds:
          - pnpx webpack
